### ISSUE TITLE
Magnetic compass and HSI both show true heading.

### ISSUE THREAD

**Issue by Jedi1-4** [Kinkkujuustovoileipa/uh-60l#226] opened 2022-12-03 07:31 UTC
HSI's and magnetic compass should both show magnetic heading.

Currently they both match true heading from F10.

**Comment by twanmal** [comment] 2023-07-12 22:05
I've just corrected the bug localy on my machine, both show now the magnetic Heading. As i'm a beginner with github pull requests could you tell me how I can do that ? and from which release ?
regards
Twan

**Comment by sniporbob** [comment] 2023-07-17 04:49
The way I've been doing it is to fork the main repository, then make a new branch within your fork. Make your change/fix in your new branch, and then from your branch you can perform a pull request on the main repository. If you do it that way every time you tackle a bug, then you will have a clean fresh branch containing nothing but the changes for that particular bug.

But take all that with a grain of salt. I'm somewhat of a github noob too, but this method seems to work nicely and make individual issues and fixes easy to track separately. There's probably a better way to do it but this method is simple.

**Comment by shearn89** [comment] 2023-07-18 08:17
You can also mention the issue number in the commit or PR, and it will link here and update as needed: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls

**Comment by twanmal** [comment] 2023-07-31 11:56
Ok, so I tried some stuff the last hours but I was not successful. The magnetic heading is shown but when going around 356 to 004 the needle stays blocked at 0. Could I see it with you anytime on discord or so ? Do you still want my update ?

**Comment by nmielcarek** [comment] 2023-07-31 17:10
Sounds like that could be a simple wrap-around issue.

Something like this:
if (mag_hdg < 0.0) mag_hdg += 360.0;
if (mag_hdg > 360.0) mag_hdg -= 360.0;

**Comment by sniporbob** [comment] 2023-07-31 22:01
You can do a bit of debugging if you'd like by adding some message printing code next to one of your changes. It takes the following form:
`print_message_to_user(variableName)`
where `variableName` is the variable from the code that you want to see in game.
It will create a message in the top right corner of the game (near the radio menu) that will display whatever variable you specify.
So you could add something like `print_message_to_user("calculated heading: "..aircraftHeading)` and it would display the calculated heading in the top right corner with the following message format:
calculated heading: ###
(You would see the value for aircraftHeading in place of ###)
This lets you see what's happening behind the scenes in the 356 to 004 range.

**Comment by shearn89** [comment] 2023-08-01 06:23
> Sounds like that could be a simple wrap-around issue.
> 
> 
> 
> Something like this:
> 
> if (mag_hdg < 0.0) mag_hdg += 360.0;
> 
> if (mag_hdg > 360.0) mag_hdg -= 360.0;

I'd expect there's a 'modulo' operator in Lua that does this without having to add logic. E.g:

mag_hdg = mag_hdg % 360

**Comment by twanmal** [comment] 2023-08-01 08:03
> I'd expect there's a 'modulo' operator in Lua that does this without having to add logic. E.g:
> 
> mag_hdg = mag_hdg % 360

this is clearly by far the most elegant way to solve this. I will upload soon

**Comment by twanmal** [comment] 2023-08-01 16:42
after making a pull request I have an error with a file : 
![image](https://github.com/Kinkkujuustovoileipa/uh-60l/assets/1897777/aee6fecb-bb51-4e9d-9b29-a4f3ff223f16)

Anyone knows how to correct it ?

**Comment by shearn89** [comment] 2023-08-01 20:25
It's a merge conflict: you can use the tools in the browser to edit the file, and make it look the way you want it to. You'll have to remove the <<<, ===, >>> as well.

Here's a guide, not sure how technical it is though! https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by shearn89** [comment] 2023-08-01 20:26
Effectively you'll want to remove lines 39-43, replacing them with JUST line 40.

**Comment by nmielcarek** [comment] 2023-08-02 03:58
I'm curious why 360 was being subtracted from the front since that would reverse the heading being displayed. If that's not desired than leave it out of course.

**Comment by twanmal** [comment] 2023-08-02 09:06
I tried with no joy this morning, the first error I have is 
![image](https://github.com/Kinkkujuustovoileipa/uh-60l/assets/1897777/3986fb61-9143-4f59-ba5a-3f56d6884d63)
telling me I have no right access to the main repository, but I made a commit to version 1.3.2.
Any advice ?

**Comment by shearn89** [comment] 2023-08-02 10:07
So you won't have permission to merge the change, but you should have the ability to fix the conflicts. It won't let me see what the conflict is though, and it looks okay to me...

Let me try replicating your change.

**Comment by shearn89** [comment] 2023-08-02 10:18
Looks to have worked okay - I created a fork from 'main', made my change in a branch, then raised the PR. You may have made your fork from a tag, which might be the cause of the issue... Anyways - looks good - have you tested locally?

**Comment by twanmal** [comment] 2023-08-02 11:08
I tested it particularly on the points where it was problematic ie at North and on the 3 devices ( compass, HSI right, HSI left ).
As the correction in core.lua was enough to let the left HSI working too, I made no correction in the CISPcopilot.lua file.
I did not tested it in regard to navigation. If someone catches a bug while navigating or anything else I would research with joy !

**Comment by shearn89** [comment] 2023-08-02 13:07
Cool, sounds good!

**Closed** 2023-09-14 22:14 UTC
Labels: bug, fixed
