### ISSUE TITLE
M130 Dispenser Incorrect

### ISSUE THREAD

**Issue by hawkgun** [Kinkkujuustovoileipa/uh-60l#14] opened 2022-01-22 04:56 UTC
The M130 Chaff Dispenser is oriented incorrectly.  Chaff shoots upwards into the rotor system for dispersion of the metal fragments to create a metal cloud which is supposed to assist in defeating radar systems.  Currently the dispenser is pointed down, which would be for flares.  The CMWS system for flares contains two dispensers.  One on each side of the tail cone pointing downwards.

**Comment by Kinkkujuustovoileipa** [comment] 2022-02-10 18:50
Closing as duplicate of https://github.com/Kinkkujuustovoileipa/uh-60l/issues/155 which has more info

**Closed by Kinkkujuustovoileipa** 2022-02-10 18:50 UTC
Labels: correction
